### ISSUE TITLE
how to pull background of radar?

### ISSUE THREAD

**Issue by primeoc** [maddenp/bomradarloop#8]
import os
import bomradarloop

outdir = ""
outfile = os.path.join(outdir, "radar.gif")
bomradarloop.BOMRadarLoop(location='Brisbane', outfile=outfile,)

How would I pull just the background of this radar loop? Basically, how to use the _background() function?

**Comment by maddenp** [comment]
Hi @primeoc. The following works for me:
```
>>> from bomradarloop import BOMRadarLoop
>>> BOMRadarLoop(location="Brisbane")._background.save("brisbane-background.png")
```
The `_background` property on a `BOMRadarLoop` object returns a [Pillow `Image` object](https://pillow.readthedocs.io/en/stable/reference/Image.html), whose `save()` method can be called to write the in-memory image to a file.

I hope that helps.

**Comment by primeoc** [comment]
Awesome, that works for me thanks! Is there any way to get the background with the Copyright attribution at the top of the image?

**Comment by maddenp** [comment]
No, the copyright is part of the radar images, not the topography, range, or place images.
